export const ROOT_LOGIN = '/'
export const LOGIN_EMAIL_ROUTE = '/login-email'
export const SIGN_UP_EMAIL_ROUTE = '/sign-up-email'
export const HOME_ROUTE = '/home'
export const CREATE_PROFILE_ROUTE = '/create-profile'
