export const ROOT_LOGIN = '/'
export const LOGIN_EMAIL_ROUTE = '/login-email'
export const SIGN_UP_EMAIL_ROUTE = '/sign-up-email'
export const CREATE_PROFILE_ROUTE = '/create-profile'

export const HOME_ROUTE = '/home'
export const BIRD_ID_ROUTE = HOME_ROUTE + '/bird-id'
export const BIRDPEDIA_ROUTE = HOME_ROUTE + '/birdpedia'
export const SETTINGS_ROUTE = HOME_ROUTE + '/settings'
export const LEADERBOARDS_ROUTE = HOME_ROUTE + '/leaderboards'
