export const ROOT = '/'
export const LOGIN_SIGN_UP = '/login-sign-up'
export const LOGIN_EMAIL_ROUTE = LOGIN_SIGN_UP + '/login-email'
export const SIGN_UP_EMAIL_ROUTE = LOGIN_SIGN_UP + '/sign-up-email'
export const CREATE_PROFILE_ROUTE = '/create-profile'

export const MAIN_ROUTE = '/main'
export const HOME_ROUTE = MAIN_ROUTE + '/home'
export const BIRD_ID_ROUTE = MAIN_ROUTE + '/bird-id'
export const BIRDPEDIA_ROUTE = MAIN_ROUTE + '/birdpedia'
export const SETTINGS_ROUTE = MAIN_ROUTE + '/settings'
export const LEADERBOARDS_ROUTE = MAIN_ROUTE + '/leaderboards'
