export const ROOT = '/'
export const LOGIN_SIGN_UP_ROUTE = '/login-sign-up'
export const LOGIN_EMAIL_ROUTE = LOGIN_SIGN_UP_ROUTE + '/login-email'
export const SIGN_UP_EMAIL_ROUTE = LOGIN_SIGN_UP_ROUTE + '/sign-up-email'
export const CREATE_PROFILE_ROUTE = '/create-profile'

export const MAIN_ROUTE = '/main'
export const HOME_ROUTE = MAIN_ROUTE + '/home'
export const BIRD_ID_ROUTE = MAIN_ROUTE + '/bird-id'
export const BIRDPEDIA_ROUTE = MAIN_ROUTE + '/birdpedia'
export const SETTINGS_ROUTE = MAIN_ROUTE + '/settings'
export const LEADERBOARDS_ROUTE = MAIN_ROUTE + '/leaderboards'

export const AUTH_CALLBACK_ROUTE = '/auth/callback'
export const AUTH_EMAIL_CONFIRM_ROUTE = '/auth/confirm'
export const ERROR_ROUTE = '/error'

const API_ROUTE = '/api'
const USERS_ROUTE = API_ROUTE + '/users'
export const CREATE_PROFILE_API_ROUTE = USERS_ROUTE + '/create-profile'
export const GET_CURRENT_USER_ROUTE = USERS_ROUTE + '/get-current-user'
const BIRDS_ROUTE = API_ROUTE + '/birds'
export const SEARCH_BIRDS_ROUTE = BIRDS_ROUTE + '/search-birds'
